version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autocannon
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.5.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: fastify-error
    versions:
    - 0.3.0
